# Generated by Django 5.1.6 on 2025-08-30 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
